version: '3.8'

services:
  db1:
    image: postgres:15.5
    container_name: postgres_db1
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: database1
    ports:
      - "5435:5432"
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user1", "-d", "database1" ]
      interval: 1s
      timeout: 1s
      retries: 60
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db2:
    image: postgres:15.5
    container_name: postgres_db2
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: database2
    ports:
      - "5433:5432"
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user2", "-d", "database2" ]
      interval: 1s
      timeout: 1s
      retries: 60
    extra_hosts:
      - "host.docker.internal:host-gateway"
