version: '3.8'

services:
  db1:
    image: postgres:15.5
    container_name: postgres_db1
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: database1
    ports:
      - "5435:5435"
    volumes:
      - /db1_data/:/var/lib/postgresql/data

  db2:
    image: postgres:15.5
    container_name: postgres_db2
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: database2
    ports:
      - "5433:5433"
    volumes:
      - /db2_data/:/var/lib/postgresql/data

volumes:
  db1_data:
  db2_data:
